services:
  collab-server:
    build: ./server
    expose:
      - "8025"

  collab-client:
    build: ./client
    depends_on:
      - collab-server
    stdin_open: true
    tty: true

  redis:
    image: redis:7
    ports:
      - "6379:6379"
