services:
  collab-server:
    build: ./server
    container_name: collab-src.main.java.server
    ports:
      - "8025:8025"

  collab-client:
    build: ./client
    depends_on:
      - collab-server
    stdin_open: true
    tty: true
